//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdBanner_View
    {
        public string AdID { get; set; }
        public string StoreID { get; set; }
        public Nullable<System.DateTime> ADate { get; set; }
        public string Kind { get; set; }
        public int BL_ID { get; set; }
        public int SortNO { get; set; }
        public string Subject { get; set; }
        public string Contents { get; set; }
        public string PicsName { get; set; }
        public string NwID { get; set; }
        public string Sidno { get; set; }
        public string ScID { get; set; }
        public string Midno { get; set; }
        public string URL { get; set; }
        public bool IsWebOn { get; set; }
        public bool IsShow { get; set; }
        public string Memo { get; set; }
        public string Esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string BL_Name { get; set; }
    }
}
