//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarCode_Prt
    {
        public int pid { get; set; }
        public string eSNO { get; set; }
        public int SortNO { get; set; }
        public string Pidno { get; set; }
        public string Midno { get; set; }
        public string ApplyID { get; set; }
        public int Nums { get; set; }
        public long mpid { get; set; }
        public bool IsMail { get; set; }
        public int EmailID { get; set; }
        public bool Isflag { get; set; }
    }
}
