//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyData1
    {
        public long cd_id { get; set; }
        public string cd_nickname { get; set; }
        public string cd_name { get; set; }
        public string cd_ename { get; set; }
        public string cd_mainperson { get; set; }
        public string cd_sid { get; set; }
        public string cd_medid { get; set; }
        public string cd_unify { get; set; }
        public string cd_invoice { get; set; }
        public string cd_note { get; set; }
        public string cd_baddress { get; set; }
        public string cd_daddress { get; set; }
        public decimal cd_capital { get; set; }
        public System.DateTime cd_adate { get; set; }
        public string cd_bitem { get; set; }
        public Nullable<System.DateTime> cd_ldate { get; set; }
        public Nullable<System.DateTime> cd_memdate { get; set; }
    }
}
