//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyData
    {
        public string BNO { get; set; }
        public string cd_name { get; set; }
        public string cd_nickname { get; set; }
        public string NOTE { get; set; }
        public string eSNO { get; set; }
        public Nullable<System.DateTime> ODate { get; set; }
        public string BKind { get; set; }
        public string BCode { get; set; }
        public string BCity { get; set; }
        public string BAddr { get; set; }
        public string BTel { get; set; }
        public string BFax { get; set; }
        public Nullable<bool> IsClose { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string Tax_no { get; set; }
        public string Tax_resp { get; set; }
        public byte[] timestamp { get; set; }
        public string bra_shortname { get; set; }
        public string bra_ename { get; set; }
        public string bra_eaddr { get; set; }
        public string brt_id { get; set; }
        public string cur_id { get; set; }
        public string entid { get; set; }
        public Nullable<System.DateTime> entdt { get; set; }
        public string tryid { get; set; }
        public Nullable<System.DateTime> trydt { get; set; }
        public int cd_id { get; set; }
    }
}
