//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon_sub_view
    {
        public int id { get; set; }
        public Nullable<System.DateTime> NDate { get; set; }
        public string StoreID { get; set; }
        public bool IsGet { get; set; }
        public string Midno { get; set; }
        public int Cid { get; set; }
        public string Ccode { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string ApplyID { get; set; }
        public string Name { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string SystemType { get; set; }
        public double DisCountAmt { get; set; }
        public string PosNumber { get; set; }
        public string SC_Id { get; set; }
        public string SC_SId { get; set; }
        public string PicName { get; set; }
        public Nullable<System.DateTime> LimitDate { get; set; }
        public string IVNO { get; set; }
        public string Contents { get; set; }
        public Nullable<bool> IsExchange { get; set; }
        public Nullable<bool> IsBirthGift { get; set; }
        public Nullable<double> basediscount { get; set; }
        public double PayPoint { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string Esno { get; set; }
        public Nullable<long> Kind { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string getKind { get; set; }
        public string CKName { get; set; }
        public int getPoints { get; set; }
        public Nullable<int> qcbPoints { get; set; }
        public bool Isflag { get; set; }
    }
}
