//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPost
    {
        public decimal dpid { get; set; }
        public System.DateTime dpDate { get; set; }
        public string dpEsno { get; set; }
        public string dpDID { get; set; }
        public System.DateTime dpSDate { get; set; }
        public System.DateTime dpEDate { get; set; }
        public string dpMemo { get; set; }
        public string esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    }
}
