//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Detail
    {
        public string Company { get; set; }
        public string BKind { get; set; }
        public string BCity { get; set; }
        public string DName { get; set; }
        public string SortNO { get; set; }
        public string DArea { get; set; }
        public int DpID { get; set; }
        public string S_Com { get; set; }
        public string BeSNO { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string esno { get; set; }
        public bool IsPrv { get; set; }
        public string PrvEsno { get; set; }
        public bool IsMod { get; set; }
        public bool IsDel { get; set; }
        public bool IsEflow { get; set; }
        public string emlyNO { get; set; }
        public string Name { get; set; }
        public string En_Name { get; set; }
        public string BNO { get; set; }
        public string DID { get; set; }
        public bool IsSM { get; set; }
        public string Area { get; set; }
        public string PostTitle { get; set; }
        public string PostID { get; set; }
        public int LevelNo { get; set; }
        public int ELevelNum { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string IDNO { get; set; }
        public string Degree { get; set; }
        public string Major { get; set; }
        public string Skill { get; set; }
        public string Marry { get; set; }
        public Nullable<System.DateTime> Adate { get; set; }
        public Nullable<System.DateTime> TrialDate { get; set; }
        public Nullable<System.DateTime> Ldate { get; set; }
        public string Lcause { get; set; }
        public Nullable<System.DateTime> PretireDate { get; set; }
        public Nullable<System.DateTime> RetireDate { get; set; }
        public string InsureKind { get; set; }
        public string TelArea1 { get; set; }
        public string Tel1 { get; set; }
        public string Tel1Ext { get; set; }
        public string Mobile { get; set; }
        public string TelArea2 { get; set; }
        public string Tel2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string ZIP { get; set; }
        public string Zip_sub { get; set; }
        public string County { get; set; }
        public string Addr { get; set; }
        public string CZip { get; set; }
        public string CZip_sub { get; set; }
        public string CCounty { get; set; }
        public string CAddr { get; set; }
        public string Ememo { get; set; }
        public Nullable<bool> IsPartTime { get; set; }
        public Nullable<bool> IsPinHole { get; set; }
        public Nullable<bool> IsSalary { get; set; }
        public Nullable<bool> IsForeign { get; set; }
        public string CardNo { get; set; }
        public string SalarID { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> WorkNums { get; set; }
        public Nullable<double> SpecDays { get; set; }
        public string HealthNO { get; set; }
        public string LaborNO { get; set; }
        public Nullable<double> HealthNums { get; set; }
        public Nullable<double> LaborNums { get; set; }
        public string Bank { get; set; }
        public string BankBrand { get; set; }
        public string BankNO { get; set; }
        public string TaxWay { get; set; }
        public Nullable<double> RaiseNums { get; set; }
        public Nullable<double> MaimedRate { get; set; }
        public Nullable<double> TaxNums { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<bool> IsNonLeave { get; set; }
        public Nullable<bool> IsExtra { get; set; }
        public string PayWay { get; set; }
        public Nullable<System.DateTime> HealthDate { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool IsConfirm { get; set; }
        public Nullable<bool> IsUpDate { get; set; }
        public string Account { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> PdChgDate { get; set; }
        public int LogErrs { get; set; }
        public Nullable<System.DateTime> LogErrsDate { get; set; }
        public Nullable<bool> IsPics { get; set; }
        public string PicsType { get; set; }
        public bool IsIdnoPics { get; set; }
        public string IdnoPicsType1 { get; set; }
        public string IdnoPicsType2 { get; set; }
        public Nullable<bool> font { get; set; }
        public string treetype { get; set; }
        public Nullable<double> sign_id { get; set; }
        public string attr { get; set; }
        public string group_property { get; set; }
        public string mailquota { get; set; }
        public bool IsMailIn { get; set; }
        public bool IsMailOut { get; set; }
        public int IsUse { get; set; }
        public int OneMailCounts { get; set; }
        public int JustView { get; set; }
        public string mailCC { get; set; }
        public int MailCounts { get; set; }
        public string chgEsno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<System.DateTime> dflDate { get; set; }
        public Nullable<System.DateTime> nflDate { get; set; }
        public string EmailID { get; set; }
        public bool IsSMS { get; set; }
        public Nullable<bool> IsOvertime { get; set; }
        public string SysUse { get; set; }
        public int IsFWork { get; set; }
        public string DeSNO { get; set; }
        public string DeSNO2 { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsAgt { get; set; }
        public bool IsMeetingAdmin { get; set; }
        public string AuthCode { get; set; }
        public Nullable<System.DateTime> AuthCodeLimit { get; set; }
    }
}
