//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiCash_Book
    {
        public long hcbid { get; set; }
        public string Midno { get; set; }
        public Nullable<int> hcid { get; set; }
        public int hcbUse { get; set; }
        public int hcbIn { get; set; }
        public int hcbBalance { get; set; }
        public string hcbStatus { get; set; }
        public string hcbRemarks { get; set; }
        public int bonban_latest { get; set; }
        public System.DateTime hcbDate { get; set; }
        public string ApplyID { get; set; }
        public string eSNO { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public int quid { get; set; }
    }
}
