//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hklist
    {
        public decimal hk_id { get; set; }
        public string hk_storeid { get; set; }
        public string hk_url { get; set; }
        public string hk_page { get; set; }
        public string hk_str { get; set; }
        public string hk_ip { get; set; }
        public Nullable<System.DateTime> hk_date { get; set; }
    }
}
