//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invader
    {
        public int Sno { get; set; }
        public string IKind { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string TKind { get; set; }
        public string LogID { get; set; }
        public string Kind { get; set; }
        public string IPAddr { get; set; }
        public string IPstart { get; set; }
        public string IPend { get; set; }
        public string Memo { get; set; }
        public string Esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    }
}
