//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string SkindNo { get; set; }
        public string ItemNO { get; set; }
        public System.DateTime ITdate { get; set; }
        public bool OnLine { get; set; }
        public int SortNo { get; set; }
        public string Item1 { get; set; }
        public string En_Item { get; set; }
        public string IName { get; set; }
        public string Memo { get; set; }
        public string Esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string Item11 { get; set; }
    }
}
