//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberSMS_View
    {
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string StoreID { get; set; }
        public string Kind { get; set; }
        public string PushType { get; set; }
        public string SPics { get; set; }
        public string LPics { get; set; }
        public string TitleName { get; set; }
        public string Subject { get; set; }
        public string SubTitle { get; set; }
        public string SMSkind { get; set; }
        public string SMSid { get; set; }
        public string SMSisMeb { get; set; }
        public string SMSmidno { get; set; }
        public int SendNums { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string S_Com { get; set; }
        public string Store_Name { get; set; }
        public int msID { get; set; }
        public int sbid { get; set; }
        public long bcid { get; set; }
        public string frmType { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public string Content { get; set; }
        public string SubSubject { get; set; }
        public string WUrl { get; set; }
    }
}
