//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Grp
    {
        public int mbgid { get; set; }
        public System.DateTime mbgDate { get; set; }
        public double mgbSortNO { get; set; }
        public string mgbName { get; set; }
        public string mgbMemo { get; set; }
        public string mgbEsno { get; set; }
        public System.DateTime mgbUDate { get; set; }
        public bool Isflag { get; set; }
    }
}
