//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberSMS_SendList
    {
        public long mssid { get; set; }
        public System.DateTime mssDate { get; set; }
        public string mssLang { get; set; }
        public string frmKind { get; set; }
        public string PushType { get; set; }
        public long msID { get; set; }
        public long mpid { get; set; }
        public string TitleName { get; set; }
        public string SubTitle { get; set; }
        public string StoreID { get; set; }
        public string StoreName { get; set; }
        public string mssEsno { get; set; }
        public string mssMidno { get; set; }
        public string mssName { get; set; }
        public string mssMobile { get; set; }
        public string SMSstring { get; set; }
        public bool IsSend { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public int SendStatus { get; set; }
        public string SendError { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public bool Isflag { get; set; }
    }
}
