//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Join
    {
        public long mjid { get; set; }
        public string Midno { get; set; }
        public System.DateTime Ndate { get; set; }
        public string StoreID { get; set; }
        public string Sidno { get; set; }
        public string MKind { get; set; }
        public bool IsRecive { get; set; }
        public bool IsSMS { get; set; }
        public double TotalAmt { get; set; }
        public double TotalHiCash { get; set; }
        public string JoinNote { get; set; }
        public bool Isflag { get; set; }
    }
}
