//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Auth
    {
        public long sid { get; set; }
        public string Midno { get; set; }
        public string CheckCodeResult { get; set; }
        public bool IsSuccess { get; set; }
        public Nullable<System.DateTime> AuthTime { get; set; }
        public string userMobile { get; set; }
        public string userIP { get; set; }
        public bool IsSMSsend { get; set; }
        public Nullable<System.DateTime> SMSdate { get; set; }
        public string SMScode { get; set; }
        public int IsSMSok { get; set; }
        public string SMSerrors { get; set; }
        public bool Isflag { get; set; }
    }
}
