//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPh
    {
        public long mpid { get; set; }
        public System.DateTime mpdate { get; set; }
        public string mpKind { get; set; }
        public string mpStoreID { get; set; }
        public string Esno { get; set; }
        public string Midno { get; set; }
        public string mpIMEI { get; set; }
        public string mpMobile { get; set; }
        public string mpPhoneType { get; set; }
        public string Vers { get; set; }
        public string AppVers { get; set; }
        public double mpPhoneSize { get; set; }
        public string mpOS { get; set; }
        public string mpDeviceID { get; set; }
        public bool mpIsSMS { get; set; }
        public bool Isflag { get; set; }
    }
}
