//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string Midno { get; set; }
        public System.DateTime Mdate { get; set; }
        public string Kind { get; set; }
        public string MKind { get; set; }
        public string FrmType { get; set; }
        public int FrmSC_Id { get; set; }
        public string FrmOther { get; set; }
        public bool IsAuthCheck { get; set; }
        public Nullable<System.DateTime> AuthCheckTime { get; set; }
        public string AuthCode { get; set; }
        public Nullable<System.DateTime> AuthCodeLimit { get; set; }
        public bool IsReSet { get; set; }
        public bool IsDel { get; set; }
        public bool IsBad { get; set; }
        public string Area { get; set; }
        public string CrNO { get; set; }
        public string mCrNO { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Zip { get; set; }
        public string Zip_sub { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public string Addr { get; set; }
        public string SName { get; set; }
        public string SSex { get; set; }
        public string SZip { get; set; }
        public string SZip_sub { get; set; }
        public string SCounty { get; set; }
        public string STown { get; set; }
        public string SAddr { get; set; }
        public string STel { get; set; }
        public string SMobile { get; set; }
        public string SEmail { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceBuyName { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceTitle { get; set; }
        public string memo { get; set; }
        public string Account_chat { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Passwordword { get; set; }
        public string FBID { get; set; }
        public string GoogleID { get; set; }
        public string LineID { get; set; }
        public string LogIP { get; set; }
        public string App_FBID { get; set; }
        public string App_GoogleID { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<System.DateTime> LoginTimeprv { get; set; }
        public int LoginErr { get; set; }
        public Nullable<System.DateTime> LoginErrTime { get; set; }
        public string LoginErrIP { get; set; }
        public bool IsGetGift { get; set; }
        public string Esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string C____以下待整理Start____ { get; set; }
        public string FName { get; set; }
        public string eCrNO { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public string PicsName { get; set; }
        public string LPicsName { get; set; }
        public bool IsAotpCheck { get; set; }
        public bool IsChk { get; set; }
        public bool IsInStore { get; set; }
        public bool IsGetVINO { get; set; }
        public string token { get; set; }
        public bool IsSMS { get; set; }
        public bool IsEpaper { get; set; }
        public bool IsFeedBack { get; set; }
        public bool IsPdCount { get; set; }
        public string C____以下待整理End____ { get; set; }
        public Nullable<System.DateTime> UpGradeDate { get; set; }
        public Nullable<System.DateTime> LevelDate { get; set; }
        public Nullable<bool> CrLost { get; set; }
        public int nowPoint { get; set; }
        public int nextPoint { get; set; }
        public int threePoint { get; set; }
        public bool IsStop { get; set; }
        public Nullable<System.DateTime> FstCdate { get; set; }
        public double FstCamt { get; set; }
        public bool Isflag { get; set; }
        public string C____以下傳金旭Start____ { get; set; }
        public string PosType { get; set; }
        public bool PosIsflag { get; set; }
        public Nullable<System.DateTime> PosTime { get; set; }
        public string PosError { get; set; }
        public string C____以下傳金旭End____1 { get; set; }
        public string C____以下待整理Start____1 { get; set; }
        public string C____以下待整理End____1 { get; set; }
    }
}
