//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FullonHotelEntities : DbContext
    {
        public FullonHotelEntities()
            : base("name=FullonHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdBanner> AdBanners { get; set; }
        public virtual DbSet<App_system> App_system { get; set; }
        public virtual DbSet<Banner_Location> Banner_Location { get; set; }
        public virtual DbSet<BarCode_Prt> BarCode_Prt { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<City_Sub> City_Sub { get; set; }
        public virtual DbSet<CompanyData1> CompanyData1 { get; set; }
        public virtual DbSet<Contact_Us> Contact_Us { get; set; }
        public virtual DbSet<coupon> coupons { get; set; }
        public virtual DbSet<coupon_Kind> coupon_Kind { get; set; }
        public virtual DbSet<coupon_LevelSub> coupon_LevelSub { get; set; }
        public virtual DbSet<coupon_sub> coupon_sub { get; set; }
        public virtual DbSet<Depart> Departs { get; set; }
        public virtual DbSet<DepartBom> DepartBoms { get; set; }
        public virtual DbSet<DuplicateLogin> DuplicateLogins { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FKind> FKinds { get; set; }
        public virtual DbSet<hklist> hklists { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Item_Sub> Item_Sub { get; set; }
        public virtual DbSet<Loginout> Loginouts { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Member_Auth> Member_Auth { get; set; }
        public virtual DbSet<Member_CrNO> Member_CrNO { get; set; }
        public virtual DbSet<Member_Grp> Member_Grp { get; set; }
        public virtual DbSet<Member_GrpUser> Member_GrpUser { get; set; }
        public virtual DbSet<Member_Join> Member_Join { get; set; }
        public virtual DbSet<Member_Level> Member_Level { get; set; }
        public virtual DbSet<Member_LevelHis> Member_LevelHis { get; set; }
        public virtual DbSet<MemberPh> MemberPhs { get; set; }
        public virtual DbSet<MemberSM> MemberSMS { get; set; }
        public virtual DbSet<MemberSMS_SendList> MemberSMS_SendList { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_Grp> News_Grp { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<OnSale> OnSales { get; set; }
        public virtual DbSet<OnSales_Pidno> OnSales_Pidno { get; set; }
        public virtual DbSet<OnSales_Rate> OnSales_Rate { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_INVO> Order_INVO { get; set; }
        public virtual DbSet<Order_Sub> Order_Sub { get; set; }
        public virtual DbSet<Promote> Promotes { get; set; }
        public virtual DbSet<Promote_Sub> Promote_Sub { get; set; }
        public virtual DbSet<QCash_Book> QCash_Book { get; set; }
        public virtual DbSet<Right> Rights { get; set; }
        public virtual DbSet<Schedule_Circle> Schedule_Circle { get; set; }
        public virtual DbSet<Schedule_File> Schedule_File { get; set; }
        public virtual DbSet<Schedule_Main> Schedule_Main { get; set; }
        public virtual DbSet<Schedule_Page> Schedule_Page { get; set; }
        public virtual DbSet<Schedule_Reply> Schedule_Reply { get; set; }
        public virtual DbSet<Schedule_ToDo> Schedule_ToDo { get; set; }
        public virtual DbSet<SKind> SKinds { get; set; }
        public virtual DbSet<SpecOrder_ApplyID> SpecOrder_ApplyID { get; set; }
        public virtual DbSet<SpecOrderApply> SpecOrderApplies { get; set; }
        public virtual DbSet<SpecOrderInfo> SpecOrderInfoes { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<SubCompany> SubCompanies { get; set; }
        public virtual DbSet<SubCompany_Sub> SubCompany_Sub { get; set; }
        public virtual DbSet<SysData> SysDatas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<YearWorkHour> YearWorkHours { get; set; }
        public virtual DbSet<ChkUpload> ChkUploads { get; set; }
        public virtual DbSet<Coupon_Book> Coupon_Book { get; set; }
        public virtual DbSet<Invader> Invaders { get; set; }
        public virtual DbSet<OnSales_Record> OnSales_Record { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Promote_LevelSub> Promote_LevelSub { get; set; }
        public virtual DbSet<SubCompany_Kind> SubCompany_Kind { get; set; }
        public virtual DbSet<ChangeProduct_View> ChangeProduct_View { get; set; }
        public virtual DbSet<City_View> City_View { get; set; }
        public virtual DbSet<CompanyData> CompanyDatas { get; set; }
        public virtual DbSet<coupon_LevelSub_View> coupon_LevelSub_View { get; set; }
        public virtual DbSet<coupon_sub_view> coupon_sub_view { get; set; }
        public virtual DbSet<DPost> DPosts { get; set; }
        public virtual DbSet<DPost_View> DPost_View { get; set; }
        public virtual DbSet<HiCash_Book> HiCash_Book { get; set; }
        public virtual DbSet<mebSMS_View> mebSMS_View { get; set; }
        public virtual DbSet<MemberPh_ViewStore> MemberPh_ViewStore { get; set; }
        public virtual DbSet<OnSales_Pidno_View> OnSales_Pidno_View { get; set; }
        public virtual DbSet<OnSales_Rate_View> OnSales_Rate_View { get; set; }
        public virtual DbSet<OnSales_Record_View> OnSales_Record_View { get; set; }
        public virtual DbSet<Promote_LevelSub_View> Promote_LevelSub_View { get; set; }
        public virtual DbSet<Rights_View> Rights_View { get; set; }
        public virtual DbSet<Schedule_Main_View> Schedule_Main_View { get; set; }
        public virtual DbSet<SKind_View> SKind_View { get; set; }
        public virtual DbSet<SubCompany_Sub_View> SubCompany_Sub_View { get; set; }
        public virtual DbSet<SubCompany_V> SubCompany_V { get; set; }
        public virtual DbSet<SubCompany_View> SubCompany_View { get; set; }
        public virtual DbSet<AdBanner_View> AdBanner_View { get; set; }
        public virtual DbSet<coupon_View> coupon_View { get; set; }
        public virtual DbSet<Depart_View> Depart_View { get; set; }
        public virtual DbSet<Employee_Detail> Employee_Detail { get; set; }
        public virtual DbSet<MemberSMS_View> MemberSMS_View { get; set; }
        public virtual DbSet<News_View> News_View { get; set; }
        public virtual DbSet<Product_View> Product_View { get; set; }
        public virtual DbSet<SpecOrderInfo_View> SpecOrderInfo_View { get; set; }
    }
}
