//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string NwID { get; set; }
        public Nullable<System.DateTime> NDate { get; set; }
        public string StoreID { get; set; }
        public string Sidno { get; set; }
        public int Kind { get; set; }
        public int Grp_ID { get; set; }
        public string Vers { get; set; }
        public bool IsOnLine { get; set; }
        public bool IsTop { get; set; }
        public bool IsBanner { get; set; }
        public double SortNO { get; set; }
        public string Subject { get; set; }
        public string SubTitle { get; set; }
        public string Contents { get; set; }
        public string Keywords { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDesc { get; set; }
        public string MetaKeywords { get; set; }
        public string ogTitle { get; set; }
        public string ogDesc { get; set; }
        public string ogURL { get; set; }
        public string ogIMG { get; set; }
        public string ogPicsType { get; set; }
        public string PicsName { get; set; }
        public string PicsType { get; set; }
        public string FileType { get; set; }
        public string frmURL { get; set; }
        public string toURL { get; set; }
        public int HitNums { get; set; }
        public string PostedOrigin { get; set; }
        public string PostedOriginUrl { get; set; }
        public int ViewCount { get; set; }
        public string WebTag { get; set; }
        public Nullable<int> YearNews { get; set; }
        public string Place { get; set; }
        public string PicName { get; set; }
        public string memo { get; set; }
        public string Esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string NCity { get; set; }
        public string summary { get; set; }
        public bool Isflag { get; set; }
    }
}
