//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Grp
    {
        public int Grp_ID { get; set; }
        public string StoreID { get; set; }
        public string GrpKind { get; set; }
        public int SortNo { get; set; }
        public string GrpName { get; set; }
        public string En_GrpName { get; set; }
        public string Sm_GrpName { get; set; }
        public bool OnLine { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public bool Isflag { get; set; }
    }
}
