//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public decimal noid { get; set; }
        public System.DateTime noDate { get; set; }
        public string noEsno { get; set; }
        public string noKind { get; set; }
        public string noSubject { get; set; }
        public string noContent { get; set; }
        public Nullable<System.DateTime> noChkDate { get; set; }
        public int noNums { get; set; }
        public string noValue { get; set; }
        public string noMidno { get; set; }
        public string noPrg { get; set; }
        public string noPgID { get; set; }
        public string noFmName { get; set; }
        public string noFmTarget { get; set; }
        public string noTbID { get; set; }
        public string noTbName { get; set; }
        public Nullable<System.DateTime> noActDate { get; set; }
        public Nullable<System.DateTime> noReadDate { get; set; }
    }
}
