//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnSale
    {
        public long said { get; set; }
        public System.DateTime saDate { get; set; }
        public bool OnLine { get; set; }
        public string saName { get; set; }
        public Nullable<System.DateTime> saSDate { get; set; }
        public Nullable<System.DateTime> saEDate { get; set; }
        public int saCost { get; set; }
        public int saNow { get; set; }
        public string saDesc { get; set; }
        public string saBanner { get; set; }
        public string Esno { get; set; }
        public System.DateTime UDate { get; set; }
        public Nullable<int> SortNo { get; set; }
        public string summary { get; set; }
        public Nullable<System.TimeSpan> saSTime { get; set; }
        public Nullable<System.TimeSpan> saETime { get; set; }
        public Nullable<int> saFreeLimit { get; set; }
        public string PicsName { get; set; }
        public bool isDel { get; set; }
        public bool Isflag { get; set; }
    }
}
