//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Sub
    {
        public long OSId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Acc { get; set; }
        public string AccName { get; set; }
        public Nullable<int> Amount { get; set; }
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> Num { get; set; }
        public string ARNO { get; set; }
        public long OId { get; set; }
        public bool Isflag { get; set; }
    }
}
