//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OId { get; set; }
        public string Midno { get; set; }
        public int SC_Id { get; set; }
        public int SC_SId { get; set; }
        public int INVOamt { get; set; }
        public int TotalAmount { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> Odate { get; set; }
        public Nullable<System.DateTime> Otime { get; set; }
        public int Bonus { get; set; }
        public bool Isflag { get; set; }
    }
}
