//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_View
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public bool IsDel { get; set; }
        public bool Online { get; set; }
        public string Pidno { get; set; }
        public int SortNo { get; set; }
        public string FKindNO { get; set; }
        public string SKindNO { get; set; }
        public string ItemNO { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Unit { get; set; }
        public string Spec { get; set; }
        public double Price { get; set; }
        public int SafeNum { get; set; }
        public double Stocks { get; set; }
        public string memo { get; set; }
        public bool Pics { get; set; }
        public string PicsType { get; set; }
        public string PicsName { get; set; }
        public string PicsLargeType { get; set; }
        public bool PicsLarge { get; set; }
        public string PicsLargeName { get; set; }
        public bool PicsSmall { get; set; }
        public string PicsSmallType { get; set; }
        public string PicsSmallName { get; set; }
        public string Esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public double TotalAmt { get; set; }
        public string Fkind { get; set; }
        public double Sprice { get; set; }
        public string PicName { get; set; }
    }
}
