//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promote_Sub
    {
        public int pmids { get; set; }
        public string pmid { get; set; }
        public int SortNO { get; set; }
        public Nullable<int> Price_id { get; set; }
        public string Pidno { get; set; }
        public string Kind { get; set; }
        public bool IsTop { get; set; }
        public double Amount { get; set; }
        public string Subject { get; set; }
        public string En_Subject { get; set; }
        public string Sm_Subject { get; set; }
        public string SubTitle { get; set; }
        public string En_SubTitle { get; set; }
        public string Sm_SubTitle { get; set; }
        public int QTY { get; set; }
        public double Price { get; set; }
        public int DiscountMoney { get; set; }
        public int GiftPoints { get; set; }
        public string BarCode { get; set; }
        public bool Isflag { get; set; }
    }
}
