//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCash_Book
    {
        public int qcbid { get; set; }
        public Nullable<int> qcid { get; set; }
        public string qcbKind { get; set; }
        public Nullable<int> bonred_id { get; set; }
        public Nullable<int> bonsue_id { get; set; }
        public string user_id { get; set; }
        public int qcbUse { get; set; }
        public int qcbIn { get; set; }
        public string qcbStatus { get; set; }
        public string qcbRemarks { get; set; }
        public int qcbBalance { get; set; }
        public int bonban_latest { get; set; }
        public System.DateTime qcbDate { get; set; }
        public string Midno { get; set; }
        public int quid { get; set; }
        public string eSNO { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public bool IsOut { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string OutName { get; set; }
        public string ApplyID { get; set; }
        public Nullable<int> said { get; set; }
        public Nullable<int> Cid { get; set; }
        public string pmid { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public bool Isflag { get; set; }
    }
}
