//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights_View
    {
        public decimal ID { get; set; }
        public string eSNO { get; set; }
        public string PgID { get; set; }
        public bool IsAdd { get; set; }
        public bool IsMod { get; set; }
        public bool IsQry { get; set; }
        public bool IsDel { get; set; }
        public bool IsChk { get; set; }
        public bool IsValid { get; set; }
        public int sno { get; set; }
        public string Pename { get; set; }
        public string Pname { get; set; }
        public bool IsMobile { get; set; }
        public string PrgFolder { get; set; }
        public string Prg { get; set; }
        public string PrgType { get; set; }
        public string Start { get; set; }
        public string Title { get; set; }
        public string ToolBar { get; set; }
        public string MenuBar { get; set; }
        public string ScrollBars { get; set; }
        public string Resizable { get; set; }
        public string Target { get; set; }
        public bool WinPos { get; set; }
        public string Pmemo { get; set; }
    }
}
