//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public decimal ID { get; set; }
        public string eSNO { get; set; }
        public string PgID { get; set; }
        public bool IsAdd { get; set; }
        public bool IsMod { get; set; }
        public bool IsQry { get; set; }
        public bool IsDel { get; set; }
        public bool IsChk { get; set; }
        public bool IsValid { get; set; }
        public bool Isflag { get; set; }
    }
}
