//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_File
    {
        public long Schfid { get; set; }
        public string Schid { get; set; }
        public long Schnid { get; set; }
        public System.DateTime SchfDate { get; set; }
        public string SchfName { get; set; }
        public string SchfMemo { get; set; }
        public string SchfEsno { get; set; }
        public System.DateTime SchfUDate { get; set; }
    }
}
