//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Page
    {
        public int SP_ID { get; set; }
        public string SP_Type { get; set; }
        public string SP_Mode { get; set; }
        public string SP_UID { get; set; }
        public string SP_DID { get; set; }
        public string SP_Page { get; set; }
        public string SP_Mode2 { get; set; }
        public string SP_Mode2_DID { get; set; }
        public string SP_Public_Esno { get; set; }
        public string SP_Public { get; set; }
    }
}
