//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_ToDo
    {
        public int ID { get; set; }
        public string eSNO { get; set; }
        public string Toname { get; set; }
        public string Toesno { get; set; }
        public string Subject { get; set; }
        public string Context { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool IsFinish { get; set; }
    }
}
