//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Main_View
    {
        public long ID { get; set; }
        public string eSNO { get; set; }
        public string Name { get; set; }
        public string BNO { get; set; }
        public string DName { get; set; }
        public string Subject { get; set; }
        public string Context { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<int> BeginHour { get; set; }
        public string BeginMin { get; set; }
        public string EndHour { get; set; }
        public string EndMin { get; set; }
        public bool Allday { get; set; }
        public string MemberName { get; set; }
        public string Chairman { get; set; }
        public string CircleID { get; set; }
        public string MeetingID { get; set; }
        public string ArlTime { get; set; }
        public bool IsMail { get; set; }
        public Nullable<System.DateTime> SendMailTime { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string DID { get; set; }
    }
}
