//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKind
    {
        public string FkindNo { get; set; }
        public string SkindNO { get; set; }
        public System.DateTime SKdate { get; set; }
        public bool OnLine { get; set; }
        public int SortNo { get; set; }
        public string Skind1 { get; set; }
        public string En_Skind { get; set; }
        public string SName { get; set; }
        public string Memo { get; set; }
        public string Esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string Skind11 { get; set; }
    }
}
