//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecOrderApply
    {
        public int ID { get; set; }
        public double SNO { get; set; }
        public string ApplyID { get; set; }
        public string ApplyIDTS { get; set; }
        public string OutApplyid { get; set; }
        public int gids { get; set; }
        public bool IsSure { get; set; }
        public Nullable<System.DateTime> SureDate { get; set; }
        public bool IsEnd { get; set; }
        public Nullable<System.DateTime> Edate { get; set; }
        public string EndCause { get; set; }
        public bool IsChk { get; set; }
        public bool IsDel { get; set; }
        public bool IsBack { get; set; }
        public bool IsRptUpdate { get; set; }
        public int ForwarderDef { get; set; }
        public string ShipTypeNo { get; set; }
        public int Colorid { get; set; }
        public int Sizeid { get; set; }
        public int main_Price_id { get; set; }
        public Nullable<int> Price_id { get; set; }
        public string Pidno { get; set; }
        public Nullable<int> DType { get; set; }
        public string Degree { get; set; }
        public Nullable<int> Extent1 { get; set; }
        public Nullable<int> Extent2 { get; set; }
        public string PKind { get; set; }
        public string Item { get; set; }
        public string En_Item { get; set; }
        public string Sm_Item { get; set; }
        public string Type { get; set; }
        public string En_Type { get; set; }
        public string Sm_Type { get; set; }
        public string Brand { get; set; }
        public string En_Brand { get; set; }
        public string Sm_Brand { get; set; }
        public Nullable<int> Oprice { get; set; }
        public Nullable<int> Onums { get; set; }
        public Nullable<int> OutNums { get; set; }
        public Nullable<int> BackNums { get; set; }
        public Nullable<int> PrvPrice { get; set; }
        public Nullable<int> RePrice { get; set; }
        public string SPstandards { get; set; }
        public Nullable<int> TmPrice { get; set; }
        public Nullable<int> ReNum { get; set; }
        public Nullable<System.DateTime> ReDate { get; set; }
        public string Price_Version { get; set; }
        public string orderno { get; set; }
        public string paymentno { get; set; }
        public string validationno { get; set; }
        public string eshopid { get; set; }
        public string eshopsonid { get; set; }
        public string trade_status { get; set; }
        public string describe { get; set; }
        public string tempvar { get; set; }
        public string account { get; set; }
        public string paycash_type { get; set; }
        public string Reason { get; set; }
        public Nullable<int> PaymentKind { get; set; }
        public Nullable<int> PayQPrice { get; set; }
        public Nullable<int> PayCashPrice { get; set; }
        public Nullable<bool> recIsPreOrder { get; set; }
        public Nullable<bool> recIsQuoted { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public string EscrowEsno { get; set; }
        public int In_Price { get; set; }
        public int Iprice { get; set; }
        public int Sprice { get; set; }
        public Nullable<bool> IsOrderDel { get; set; }
        public Nullable<bool> IsFPurch { get; set; }
        public Nullable<int> FPurchMotherGoods { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> SourceKind { get; set; }
        public int QCash { get; set; }
        public string pmid { get; set; }
        public bool UsedPrcode { get; set; }
        public string esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string 以下為產生綠界訂單資訊 { get; set; }
        public string MerchantID { get; set; }
        public string MerchantTradeNo { get; set; }
        public int RtnCode { get; set; }
        public string RtnMsg { get; set; }
        public string AllPayLogisticsID { get; set; }
        public string LogisticsType { get; set; }
        public string LogisticsSubType { get; set; }
        public int GoodsAmount { get; set; }
        public string UpdateStatusDate { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string ReceiverCellPhone { get; set; }
        public string ReceiverEmail { get; set; }
        public string ReceiverAddress { get; set; }
        public string CVSPaymentNo { get; set; }
        public string CVSValidationNo { get; set; }
        public string BookingNote { get; set; }
        public int DiscountMoney2 { get; set; }
        public string DiscountRecord { get; set; }
        public string DiscountRecordBig { get; set; }
        public bool Isflag { get; set; }
    }
}
