//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecOrderInfo
    {
        public string ApplyID { get; set; }
        public string StoreID { get; set; }
        public int SNO { get; set; }
        public System.DateTime Adate { get; set; }
        public string status { get; set; }
        public string Kind { get; set; }
        public bool IsDel { get; set; }
        public string OrderSource { get; set; }
        public string sid { get; set; }
        public bool IsSales { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string Midno { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Currency_No { get; set; }
        public int DiscountCash { get; set; }
        public double Amount { get; set; }
        public double Account { get; set; }
        public string IP { get; set; }
        public string ReMark { get; set; }
        public string ReMemo { get; set; }
        public bool IsEnd { get; set; }
        public bool IsMod { get; set; }
        public string SZip { get; set; }
        public string SZip_sub { get; set; }
        public string SCounty { get; set; }
        public string SAddr { get; set; }
        public string SName { get; set; }
        public string STelArea { get; set; }
        public string STel { get; set; }
        public string SMobile { get; set; }
        public string SEmail { get; set; }
        public string SSex { get; set; }
        public string esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public int UseBens { get; set; }
        public int CountBens { get; set; }
        public Nullable<int> CId { get; set; }
        public Nullable<int> CSId { get; set; }
        public Nullable<int> SC_Id { get; set; }
        public Nullable<int> SC_SId { get; set; }
        public Nullable<int> said { get; set; }
        public string PayWay { get; set; }
        public Nullable<int> PayCashPrice { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public Nullable<int> OdStatus { get; set; }
        public bool Isflag { get; set; }
    }
}
