//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCompany_Sub_View
    {
        public int SC_SId { get; set; }
        public int SC_Id { get; set; }
        public string SC_SName { get; set; }
        public Nullable<System.DateTime> SC_SDate { get; set; }
        public string Esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<int> SortNo { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public string SC_Name { get; set; }
        public Nullable<bool> Online { get; set; }
        public string SC_City { get; set; }
        public string SC_County { get; set; }
        public string SC_SNO { get; set; }
        public string SC_NickName { get; set; }
    }
}
