//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysData
    {
        public int ID { get; set; }
        public int SortNO { get; set; }
        public string UpDpIDs { get; set; }
        public bool IsDelete { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public string SysName { get; set; }
        public string SysName_Eng { get; set; }
        public string SysCode { get; set; }
        public string SysParameter { get; set; }
        public bool IsGlobal { get; set; }
        public string Memo { get; set; }
        public string Esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public bool Isflag { get; set; }
    }
}
