//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearWorkHour
    {
        public decimal Awid { get; set; }
        public int IsDone { get; set; }
        public System.DateTime Awdate { get; set; }
        public bool IsHoliday { get; set; }
        public string HolidayName { get; set; }
        public double WorkHours { get; set; }
        public int IsWeek { get; set; }
        public bool Ishr09 { get; set; }
        public int hr09Nums { get; set; }
        public int hr09Chk { get; set; }
        public bool Ishr10 { get; set; }
        public int hr10Nums { get; set; }
        public int hr10Chk { get; set; }
        public bool Ishr11 { get; set; }
        public int hr11Nums { get; set; }
        public int hr11Chk { get; set; }
        public bool Ishr13 { get; set; }
        public int hr13Nums { get; set; }
        public int hr13Chk { get; set; }
        public bool Ishr14 { get; set; }
        public int hr14Nums { get; set; }
        public int hr14Chk { get; set; }
        public bool Ishr15 { get; set; }
        public int hr15Nums { get; set; }
        public int hr15Chk { get; set; }
        public string esno { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    }
}
